name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          # https://github.com/actions/setup-node#supported-version-syntax
          node-version: "lts/*"
      - run: npm i -g pnpm
      - run: pnpm i
      - run: pnpm test
